version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    overwrite: true

hooks:
  ApplicationStop:
    - location: cleanup.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: health_check.sh
      timeout: 60
      runas: root
  AfterAllowTestTraffic:
    - location: final_health_check.sh
      timeout: 60
      runas: root
