version: 1.0
os: linux
files:
  - source: scripts/cleanup.sh
    destination: /opt/scripts
  - source: scripts/install_docker.sh
    destination: /opt/scripts
  - source: scripts/start_docker.sh
    destination: /opt/scripts
  - source: scripts/stop_docker.sh
    destination: /opt/scripts
  - source: scripts/health_check.sh
    destination: /opt/scripts
  - source: scripts/final_health_check.sh
    destination: /opt/scripts

hooks:
  ApplicationStop:
    - location: /opt/scripts/cleanup.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: /opt/scripts/install_docker.sh
      timeout: 300
      runas: root
    - location: /opt/scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /opt/scripts/start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /opt/scripts/health_check.sh
      timeout: 60
      runas: root
