version: 0.0
os: linux
files:
  - source: /scripts
    destination: /home/ec2-user/thoughtMap2Backend
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/cleanup.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
