version: 0.0
os: linux
files:
  - source: target/
    destination: /var/app/target
    overwrite: true
  - source: scripts/
    destination: /var/app/scripts
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
