version: 0.0
os: linux
files:
  - source: /
    destination: /var/app

hooks:
  BeforeInstall:
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
