version: 0.0
os: linux
files:
  - source: /
    destination: /var/app
    owner: ec2-user
    group: ec2-user
  - source: scripts/cleanup.sh
    destination: scripts
  - source: scripts/install_docker.sh
    destination: scripts
  - source: scripts/stop_docker.sh
    destination: scripts

hooks:
  ApplicationStop:
    - location: scripts/cleanup.sh
      timeout: 120
      runas: root
  BeforeInstall:
    - location: scripts/install_docker.sh
      timeout: 300
      runas: root
    - location: scripts/stop_docker.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/health_check.sh
      timeout: 60
      runas: root
  AfterAllowTestTraffic:
    - location: scripts/final_health_check.sh
      timeout: 60
      runas: root
