version: 0.2
# Comments
phases:
  install:
    commands:
      - echo Installing necessary tools...
      - apt-get update && apt-get install -y awscli docker.io
      - echo Verifying installed tools...
      - which aws || echo "AWS CLI not found" && exit 1
      - which docker || echo "Docker not found" && exit 1
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-2.amazonaws.com || exit 1
  build:
    commands:
      - echo Building the Java application with Maven...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t thoughtmap-backend .
      - echo Tagging the Docker image...
      - docker tag thoughtmap-backend:latest 123456789012.dkr.ecr.us-east-2.amazonaws.com/thoughtmap-backend:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 123456789012.dkr.ecr.us-east-2.amazonaws.com/thoughtmap-backend:latest
artifacts:
  files:
    - target/*.jar
    - buildspec.yml
    - appspec.yml
    - scripts/**/*
cache:
  paths:
    - /root/.m2/repository/**/* # Maven dependencies cache
