version: 0.2
# Comments
phases:
  install:
    commands:
      - echo Installing necessary tools...
      - apt-get update && apt-get install -y awscli docker.io maven jq
      - echo Verifying installed tools...
      - if ! which aws; then echo "AWS CLI not found" && exit 1; fi
      - if ! which docker; then echo "Docker not found" && exit 1; fi
      - if ! which mvn; then echo "Maven not found" && exit 1; fi
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-2.amazonaws.com || exit 1
  build:
    commands:
      - echo Building the Java application with Maven...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t thoughtmap-backend .
      - echo Tagging the Docker image...
      - docker tag 761018876037.dkr.ecr.us-east-2.amazonaws.com/thoughtmap/service/data:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 761018876037.dkr.ecr.us-east-2.amazonaws.com/thoughtmap/service/data:latest
artifacts:
  files:
    - target/*.jar
    - buildspec.yml
    - appspec.yml
    - scripts/**/*
cache:
  paths:
    - /root/.m2/repository/**/* # Maven dependencies cache
