#!/bin/bash
echo Stopping existing Docker container...
docker stop thoughtmap-backend || true
echo Removing existing Docker container...
docker rm thoughtmap-backend || true
echo Pulling the latest image from ECR...
docker pull 123456789012.dkr.ecr.us-east-2.amazonaws.com/thoughtmap-backend:latest
echo Starting a new Docker container...
docker run -d -p 8080:8080 --name thoughtmap-backend 123456789012.dkr.ecr.us-east-2.amazonaws.com/thoughtmap-backend:latest
