services:
  backend:
    image: backend-service #761018876037.dkr.ecr.us-east-2.amazonaws.com/thoughtmap/service/data:latest
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: on-failure
    secrets:
      - mongo-uri
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=/run/secrets/mongo-uri

secrets:
  mongo-uri:
    external: true
