name: Java CI with Maven and Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: create env file
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: mattbernhardt23/backend-service
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build # This job depends on the 'build' job
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker Stack to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }} # Your EC2 instance's public IP
          username: ${{ secrets.EC2_USER }} # Default is usually 'ec2-user'
          key: ${{ secrets.EC2_PRIVATE_KEY }} # SSH private key stored in GitHub secrets
          script: |
            # Pull the latest Docker image from Docker Hub
            docker pull mattbernhardt23/backend-service:latest

            # Create or update the Docker stack
            echo "Deploying Docker stack..."
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
            docker stack deploy -c docker-stack.yml backend-stack
